# Generated by Django 4.0a1 on 2021-10-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpotato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdata',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='MealData',
        ),
    ]
