# Generated by Django 4.0a1 on 2021-10-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('healthpotato', '0003_alter_weightdata_notes_fooddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('type', models.IntegerField(choices=[(0, 'Aerobic'), (1, 'Anaerobic')])),
                ('effort', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Exercise data',
            },
        ),
    ]
