# Generated by Django 4.0b1 on 2021-10-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpotato', '0006_alter_exercisedata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdata',
            name='clothing',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Light'), (2, 'Medium'), (3, 'Heavy')], default=0),
        ),
    ]
