# Generated by Django 4.0b1 on 2021-11-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpotato', '0007_weightdata_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightdata',
            name='clothing',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Light'), (2, 'Medium'), (3, 'Heavy')], default=1),
        ),
    ]
