# Generated by Django 4.0b1 on 2021-11-07 03:18

from django.db import migrations


def expand_choices(apps, schema_editor):
    CHOICE_MAPPINGS = {
        1: 1,
        2: 3,
        3: 5,
        4: 7,
        5: 9,
    }
    ExerciseData = apps.get_model('healthpotato', 'ExerciseData')
    FoodData = apps.get_model('healthpotato', 'FoodData')

    for data in ExerciseData.objects.all():
        data.effort = CHOICE_MAPPINGS[data.effort]
        data.save()

    for data in FoodData.objects.all():
        data.nutrition = CHOICE_MAPPINGS[data.nutrition]
        data.amount = CHOICE_MAPPINGS[data.amount]
        data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('healthpotato', '0009_alter_exercisedata_effort_alter_fooddata_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(expand_choices),
    ]
